apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: db
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ClusterIP
  selector:
    app: airflow
    tier: backend
  ports:
  - port: 6379
    name: redis
    protocol: TCP
    targetPort: redis
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: NodePort
  selector:
    app: airflow
    tier: web
  ports:
  - name: web
    protocol: TCP
    port: 8080
    targetPort: web
    nodePort: 31317
---
apiVersion: v1
kind: Service
metadata:
  name: flower
spec:
  type: NodePort
  selector:
    app: airflow
    tier: flower
  ports:
    - name: flower
      protocol: TCP
      port: 5555
      targetPort: flower
      nodePort: 32081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: db
  template:
    metadata:
      labels:
        app: airflow
        tier: db
    spec:
      containers:
      - name: postgres
        image: postgres:9.6
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "400m"
        ports:
        - name: postgres
          containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: backend
  template:
    metadata:
      labels:
        app: airflow
        tier: backend
    spec:
      restartPolicy: Always
      containers:
      - name: redis
        image: redis:3.2.7
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "400m"
        ports:
        - name: redis
          containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow
        tier: web
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: airflowdagdir
          hostPath:
            path: "/data/dags/"
        - name: airflowpluginsdir
          hostPath:
            path: "/data/plugins/"
      restartPolicy: Always
      containers:
      - args:
        - webserver
        env:
        - name: EXECUTOR
          value: Celery
        - name: FERNET_KEY
          value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - name: LOAD_EX
          value: "n"
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG
          value: "1"
        image: puckel/docker-airflow:1.10.1
        name: webserver
        ports:
        - name: web
          containerPort: 8080
        volumeMounts:
          - name: airflowdagdir
            mountPath: "/usr/local/airflow/dags"
          - name: airflowpluginsdir
            mountPath: "/usr/local/airflow/plugins"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: flower
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: airflow
        tier: flower
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: airflowdagdir
          hostPath:
            path: "/data/dags/"
        - name: airflowpluginsdir
          hostPath:
            path: "/data/plugins/"
      restartPolicy: Always
      containers:
      - args:
        - flower
        env:
        - name: FLOWER_PORT
          value: "5555"
        - name: EXECUTOR
          value: Celery
        - name: FERNET_KEY
          value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - name: LOAD_EX
          value: "n"
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        image: puckel/docker-airflow:1.10.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "400m"
        name: flower
        ports:
        - name: flower
          containerPort: 5555
        volumeMounts:
          - name: airflowdagdir
            mountPath: "/usr/local/airflow/dags"
          - name: airflowpluginsdir
            mountPath: "/usr/local/airflow/plugins"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: scheduler
  template:
    metadata:
      labels:
        app: airflow
        tier: scheduler
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        fsGroup: 0
      volumes:
        - name: airflowdagdir
          hostPath:
            path: "/data/dags/"
        - name: airflowpluginsdir
          hostPath:
            path: "/data/plugins/"
      containers:
      - args:
        - scheduler
        env:
        - name: EXECUTOR
          value: Celery
        - name: FERNET_KEY
          value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - name: LOAD_EX
          value: "n"
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG
          value: "1"
        image: puckel/docker-airflow:1.10.1
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "400m"
        name: scheduler
        volumeMounts:
          - name: airflowdagdir
            mountPath: "/usr/local/airflow/dags"
          - name: airflowpluginsdir
            mountPath: "/usr/local/airflow/plugins"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      tier: worker
  template:
    metadata:
      labels:
        app: airflow
        tier: worker
    spec:
      restartPolicy: Always
      volumes:
        - name: airflowdagdir
          hostPath:
            path: "/data/dags/"
        - name: airflowpluginsdir
          hostPath:
            path: "/data/plugins/"
      containers:
      - args:
        - worker
        env:
        - name: EXECUTOR
          value: Celery
        - name: FERNET_KEY
          value: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - name: LOAD_EX
          value: "n"
        - name: POSTGRES_USER
          value: "airflow"
        - name: POSTGRES_PASSWORD
          value: "airflow"
        - name: POSTGRES_DB
          value: "airflow"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: AIRFLOW_HOME
          value: "/usr/local/airflow"
        - name: AIRFLOW__CORE__EXECUTOR
          value: CeleryExecutor
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
        - name: AIRFLOW__CELERY__RESULT_BACKEND
          value: "db+postgresql://airflow:airflow@postgres:5432/airflow"
        - name: AIRFLOW__CELERY__BROKER_URL
          value: "redis://redis:6379/1"
        - name: AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG
          value: "1"
        - name: AIRFLOW__CELERY__WORKER_CONCURRENCY
          value: "1"
        image: puckel/docker-airflow:1.10.1
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "1.5Gi"
            cpu: "400m"
        name: worker
        volumeMounts:
          - name: airflowdagdir
            mountPath: "/usr/local/airflow/dags"
          - name: airflowpluginsdir
            mountPath: "/usr/local/airflow/plugins"